internal/gapicgen: report test failures directly
This keeps the test failure and cause in the same location. t.Errorf
will continue executing the test (t.Fatalf stops execution). See
https://github.com/golang/go/wiki/TestComments#keep-going.

Also, I put the import path first since it's the more useful part for
finding the failing config. But, the import path may be empty, so I left
the index in
(https://github.com/golang/go/wiki/TestComments#identify-the-input is
relevant).

This results in failures like:
--- FAIL: TestMicrogenConfigs (0.00s)
    /.../internal/gapicgen/generator/config_test.go:43: config "cloud.google.com/go/texttospeech/apiv1" (#0) expected non-empty pkg field
    /.../internal/gapicgen/generator/config_test.go:59: config "cloud.google.com/go/language/apiv1" (#2) invalid release level: "alphaa"

Change-Id: If92888c1fd21484ea92918ebbdb362b8400a6bac
Reviewed-on: https://code-review.googlesource.com/c/gocloud/+/50810
Reviewed-by: kokoro <noreply+kokoro@google.com>
Reviewed-by: Noah Dietz <ndietz@google.com>